apiVersion: apps/v1
kind: Deployment
metadata:
  labels: &Apache1Labels
    "app.kubernetes.io/name": 'apache1'
    "app.kubernetes.io/instance": "apache1"
    "app.kubernetes.io/component": "apache1-main"
  name: apache1
  namespace: apache1
spec:
  replicas: 1
  selector:
    matchLabels: *Apache1Labels
  template:
    metadata:
      labels: *Apache1Labels
    spec:
      containers:
      - image: KUSTOMIZED
        imagePullPolicy: "IfNotPresent"
        name: apache1
        resources:
            requests:
              cpu: 512m
              memory: 1G
            limits:
              cpu: 512m
              memory: 1G