apiVersion: v1
kind: Service
metadata:
  labels:
    "app.kubernetes.io/name": 'apache1'
    "app.kubernetes.io/instance": "apache1"
    "app.kubernetes.io/component": "apache1-main"
  name: apache1-svc
  namespace: apache1
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app.kubernetes.io/name: apache1
  type: ClusterIP