apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../domokai-base/apache1
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: apache1
    namespace: apache1
  path: version-patch.yaml