---
# Source: argo-cd/templates/argocd-application-controller/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: argocd-application-controller
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-application-controller
    app.kubernetes.io/instance: argo-cd-domokai
    app.kubernetes.io/component: application-controller
    app.kubernetes.io/part-of: argocd
---
# Source: argo-cd/templates/argocd-server/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: argocd-server
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/instance: argo-cd-domokai
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: argocd
---
# Source: argo-cd/templates/dex/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: argocd-dex-server
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-dex-server
    app.kubernetes.io/instance: argo-cd-domokai
    app.kubernetes.io/component: dex-server
    app.kubernetes.io/part-of: argocd